import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/css/main.css";
import Navigation from "./components/navigation/page";
import "flowbite";
import Footer from "./components/footer/page";

<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Portfolio | Reza Bagus Pratama",
    template: "%s | Portfolio | Reza Bagus Pratama",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={`${inter.className} bg-white dark:bg-darkColor500`}>
          <div className="max-w-screen-2xl mx-auto !overflow-x-hidden">
            <Navigation />
            
            {/* notif maintenance */}
            <div className="fixed w-full z-10 left-0 top-16 flex items-center justify-center p-4 mb-4 text-sm text-yellow-800 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300" role="alert">
              <svg className="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
              </svg>
              <span className="sr-only">Info</span>
              <div>
                <span className="font-medium text-center">Warning alert!</span> This website is currently under maintenance. We apologize for the inconvenience.
              </div>
            </div>
            {/* ------ */}
            
            {children}
            <Footer />
          </div>

          <script async src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        </body>
      </html>
    </>
  );
}
